name: GCP Deploy
on:
  push:
    branches: [ main ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Login
        run: echo  ${{ secrets.ARTIFACTORY_PASSWORD }} | docker login -u ${{ secrets.ARTIFACTORY_USERNAME }} --password-stdin https://docker.artifactory.glss.ir/artifactory/docker/
      - name: GooleCloud SDK
        uses: google-github-actions?setup-gcloud@master
        with:
          version: latest
          project_id: ${{ secrets.GCP_PR_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
      - name: Deploy
        run: |
          gcloud run deploy ---servicename--- --image commit-m/rentazon:latest --platform managed --region ---region---
