name: CiCD Pipeline
on:
  push:
    branches: [ main,cicd ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: docker build -t docker.artifactory.glss.ir/commit-m/rentazon:${{ github.sha }} .
      - name: Login
        run: echo  ${{ secrets.ARTIFACTORY_PASSWORD }} | docker login -u ${{ secrets.ARTIFACTORY_USERNAME }} --password-stdin https://docker.artifactory.glss.ir/artifactory/docker/
      - name: Push
        run: docker push docker.artifactory.glss.ir/commit-m/rentazon:${{ github.sha }}
