name: CiCD Pipeline
on:
  push:
    branches: [ main,cicd ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: docker build -t commit-m/rentazon:latest .
      - name: Login
        run: echo  ${{ secrets.ARTIFACTORY_PASSWORD }} | docker login -u ${{ secrets.ARTIFACTORY_USERNAME }} --password-stdin artifactory.glss.ir
      - name: Push
        run: docker push artifactory.glss.ir/commitm/rentazon:latest
